### PR TITLE
Update to work with Java 8 and Spring 5

### PR DESCRIPTION
**Pull request by jodygarnett**
* Now uses Java 8
* Update to Spring 5
* Isolated internal repository to an optional profile
* Removed a lot of duplicate version management, trusting maven to handle transitive dependencies
* I took some notes (see README.md) on how to build
* Added a jetty configuration for local testing
* Changed the version number to `2.0.0` to indicate this is not the previous `1.0.5` release

### CODE REVIEW

**Comment by james-rae** [comment]
Hey good buddy. 

So I literally just put this up so some other team could grab it. Had planned to make it private/delete it after they grabbed this, and I didn't write this code (or even understand it 🏆 ).  I don't mind that you've forked it but be aware the license on this is unknown. I don't expect issues (a proxy for open services seems benign).

If by chance you're on the team this was intended for, I'd suggest just going forward with your fork of it.

I'll probably be making my repo private in the next day or so.  But do appreciate the PR to share these enhancements.

**Comment by jodygarnett** [comment]
> If by chance you're on the team this was intended for, I'd suggest just going forward with your fork of it.

I am indeed working with the team this was intended for, it seems a fair bit of infrastructure depends on how this specific wms proxy behaves! I am aware the code is not provided with a license, perhaps you could kindly bring this up with the team, if they wish to continue using this implementation.

**Comment by james-rae** [comment]
Thanks for lettin' me know. I'm just a middle man here but will pass along a note to my pal on the inside.
Good luck with it!

**Comment by bo-lu** [comment]
Hi James,

Jody is our contractor and is helping us fix the WMSProxy to compile in Java 8 and tomcat 8.5. The WMSProxy is being used in our app. I think we can go private soon.

Bo Lu (bo.lu@canada.ca)

**Comment by james-rae** [comment]
Excellent. I'll make my repo private at the end of the day.
Appreciate the info

**Pull request merged**
